name: Update JSON File

on:
  push:
    paths:
      - JB/valid_links2.txt  # Match the script's file name
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # Every hour

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run JSON Update Script
        env:
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}  # Use default GITHUB_TOKEN
        run: python JB/update_github_json2.py

      - name: Show updated content
        run: |
          echo "=== Updated valid_links2.txt content ==="
          cat JB/valid_links2.txt
          echo "=== Updated JSON content ==="
          cat tv/XYQHiker/黄色仓库.json
