name: Update Domain

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次

jobs:
  update-domain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install requests

    - name: Run update_domain.py script
      run: |
        echo "Running update_domain.py script..."
        python3 JB/update_domain.py

    - name: Commit and push changes (if any)
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # 检查 JB 文件夹是否有变化
        git status --untracked-files=all --short | grep "JB/" || exit 0

        git add JB/valid_links2.txt
        git commit -m "Update valid domain links"
        git push origin HEAD:main
