name: Update JSON File

on:
  push:
    paths:
      - JB/valid_links.txt  # 当 valid_links.txt 变化时触发
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: "0 * * * *"  # 每小时运行一次

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run JSON Update Script
        env:
          YOU_TOKEN: ${{ secrets.YOU_TOKEN }}  # GitHub Secrets 中的 Token
        run: python JB/update_github_json2.py

      - name: Show updated content
        run: |
          echo "=== 更新后的 valid_links.txt 文件内容 ==="
          cat JB/valid_links.txt
          echo "=== 更新后的 JSON 文件内容 ==="
          cat tv/XYQHiker/黄色仓库.json  # 使用正确的路径
